In [0]:
import pandas as pd
import numpy as np
from tensorflow.keras.utils  import to_categorical

In [1]:
import os
# print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.
import itertools
import os

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelBinarizer, LabelEncoder
from sklearn.metrics import confusion_matrix

from tensorflow import keras
layers = keras.layers
models = keras.models

In [0]:
data = pd.read_csv("/content/bbc-text .csv")

In [7]:
data

category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
1365       business  j&j agrees $25bn guidant deal pharmaceutical g...
1366           tech  broadband in the uk growing fast high-speed ne...
1367       politics  howard denies split over id cards michael howa...
1368       politics  no uk apology  for colonial past the days of b...
1369          sport  anelka  eyes man city departure  striker nicol...

[1370 rows x 2 columns]

In [8]:
data.shape

(1370, 2)

In [9]:
data.head(7)

category                                               text
0           tech  tv future in the hands of viewers with home th...
1       business  worldcom boss  left books alone  former worldc...
2          sport  tigers wary of farrell  gamble  leicester say ...
3          sport  yeading face newcastle in fa cup premiership s...
4  entertainment  ocean s twelve raids box office ocean s twelve...
5       politics  howard hits back at mongrel jibe michael howar...
6       politics  blair prepares to name poll date tony blair is...

In [10]:
train_size = int(len(data) *.8)
print ("Train size: %d" % train_size)
print ("Test size: %d" % (len(data) - train_size))

Train size: 1096
Test size: 274


In [11]:
def train_test_split(data, train_size):
    train = data[:train_size]
    test = data[train_size:]
    return train, test
train_test_split(data,train_size=train_size) 

(           category                                               text
 0              tech  tv future in the hands of viewers with home th...
 1          business  worldcom boss  left books alone  former worldc...
 2             sport  tigers wary of farrell  gamble  leicester say ...
 3             sport  yeading face newcastle in fa cup premiership s...
 4     entertainment  ocean s twelve raids box office ocean s twelve...
 ...             ...                                                ...
 1091          sport  laporte tinkers with team france coach bernard...
 1092  entertainment  rocker doherty in on-stage fight rock singer p...
 1093  entertainment  arnold congratulated on oscar win oscar-winner...
 1094       business  gold falls on imf sale concerns the price of g...
 1095          sport  african double in edinburgh world 5000m champi...
 
 [1096 rows x 2 columns],
            category                                               text
 1096           tech  internet boom 

In [0]:
train_cat, test_cat = train_test_split(data['category'], train_size)
train_text, test_text = train_test_split(data['text'], train_size)

In [13]:
train_text

0       tv future in the hands of viewers with home th...
1       worldcom boss  left books alone  former worldc...
2       tigers wary of farrell  gamble  leicester say ...
3       yeading face newcastle in fa cup premiership s...
4       ocean s twelve raids box office ocean s twelve...
                              ...                        
1091    laporte tinkers with team france coach bernard...
1092    rocker doherty in on-stage fight rock singer p...
1093    arnold congratulated on oscar win oscar-winner...
1094    gold falls on imf sale concerns the price of g...
1095    african double in edinburgh world 5000m champi...
Name: text, Length: 1096, dtype: object

In [14]:
max_words = 1000
tokenize = keras.preprocessing.text.Tokenizer(num_words=max_words, \
                                            char_level=False)
train_text

0       tv future in the hands of viewers with home th...
1       worldcom boss  left books alone  former worldc...
2       tigers wary of farrell  gamble  leicester say ...
3       yeading face newcastle in fa cup premiership s...
4       ocean s twelve raids box office ocean s twelve...
                              ...                        
1091    laporte tinkers with team france coach bernard...
1092    rocker doherty in on-stage fight rock singer p...
1093    arnold congratulated on oscar win oscar-winner...
1094    gold falls on imf sale concerns the price of g...
1095    african double in edinburgh world 5000m champi...
Name: text, Length: 1096, dtype: object

In [15]:
tokenize.fit_on_texts(train_text) # fit tokenizer to our training text data
x_train = tokenize.texts_to_matrix(train_text)
x_test = tokenize.texts_to_matrix(test_text)
x_train[0]

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0.

In [18]:
encoder = LabelEncoder()
encoder.fit(train_cat)
y_train = encoder.transform(train_cat)
y_test = encoder.transform(test_cat)
y_test.ndim

1

In [19]:
# Converts the labels to a one-hot representation
num_classes = np.max(y_train) + 1
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
y_test


array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [0]:
num_classes

5

In [20]:
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)

x_train shape: (1096, 1000)
x_test shape: (274, 1000)
y_train shape: (1096, 5)
y_test shape: (274, 5)


In [0]:
batch_size = 32
epochs = 4
drop_ratio = 0.5

In [0]:
model = models.Sequential()
model.add(layers.Dense(512, input_shape=(max_words,)))
model.add(layers.Dense(212 , activation = 'relu'))
model.add(layers.Activation('relu'))
model.add(layers.Dense(num_classes))
model.add(layers.Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])


In [37]:
history = model.fit(x_train, y_train,batch_size=batch_size,epochs=epochs,verbose=1,validation_split=0.1)

Train on 986 samples, validate on 110 samples
Epoch 1/4
986/986 [==============================] - 0s 199us/sample - loss: 0.4539 - acc: 0.8499 - val_loss: 0.2217 - val_acc: 0.9636
Epoch 2/4
986/986 [==============================] - 0s 90us/sample - loss: 0.0221 - acc: 0.9980 - val_loss: 0.1971 - val_acc: 0.9636
Epoch 3/4
986/986 [==============================] - 0s 85us/sample - loss: 0.0035 - acc: 1.0000 - val_loss: 0.2090 - val_acc: 0.9545
Epoch 4/4
986/986 [==============================] - 0s 78us/sample - loss: 0.0018 - acc: 1.0000 - val_loss: 0.2086 - val_acc: 0.9636


In [38]:
score = model.evaluate(x_test, y_test,\
                       batch_size=batch_size, verbose=1)


274/274 [==============================] - 0s 101us/sample - loss: 0.0807 - acc: 0.9745


In [39]:
print('Test loss:', score[0])
print('Test accuracy:', score[1])


Test loss: 0.08066684529729133
Test accuracy: 0.97445256


In [40]:
# model.predict(x_train[0])
x_train[0].shape

(1000,)

# Hyperparameter tunning

This is a good time to go back and tweak some parameters such as epoch, batch size, dropout ratio, network structure, activation function, and others, to see if you can improve the accuracy.

> Indented block



In this particular case, to make it more challenging, I recommend reducing the max words of the call to keras.preprocessing.text.Tokenizer. This will reduce the number of words for each input sample, thus making it more challenging to accurately predict the category. (Notice that not all hyperparameters are necessarily inside the model. This is one such example.)

The default was up to 1000 words per article. See what happens when you reduce that number to 200 words, or 50 words, or even fewer. As the evaluation accuracy drops, the effects of your hyperparameter tuning will be more pronounced, with successful adjustments making meaningful improvements to the model performance.

To make this process easier to manage, I've encapulated the model definition and training and evaluation calls into one function call. You can add additional parameters as needed.

In [0]:
#by using hyperprameter tunning

def run_experiment(batch_size, epochs, drop_ratio):
  print('batch size: {}, epochs: {}, drop_ratio: {}'.format(
      batch_size, epochs, drop_ratio))
  model = models.Sequential()
  model.add(layers.Dense(512, input_shape=(max_words,)))
  model.add(layers.Activation('relu'))
  model.add(layers.Dropout(drop_ratio))
  model.add(layers.Dense(num_classes))
  model.add(layers.Activation('softmax'))

  model.compile(loss='categorical_crossentropy',
                optimizer='adam',
                metrics=['accuracy'])
  history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=0,
                    validation_split=0.1)
  score = model.evaluate(x_test, y_test,
                       batch_size=batch_size, verbose=0)
  print('\tTest loss:', score[0])
  print('\tTest accuracy:', score[1])

In [42]:
batch_size = 16
epochs = 4
drop_ratio = 0.8
history=run_experiment(batch_size, epochs, drop_ratio)

batch size: 16, epochs: 4, drop_ratio: 0.8
	Test loss: 0.12007814732781291
	Test accuracy: 0.9708029


In [48]:
text_labels = encoder.classes_

for i in range(10):
    prediction = model.predict(np.array([x_test[i]]))
    predicted_label = text_labels[np.argmax(prediction)]
    print(test_text.iloc[i][:50], "...")
    print('Actual label:' + test_cat.iloc[i])
    print("Predicted label: " + predicted_label + "\n")  


internet boom for gift shopping cyberspace is beco ...
Actual label:tech
Predicted label: tech

ask jeeves joins web log market ask jeeves has bou ...
Actual label:tech
Predicted label: tech

bbc denies blackadder tv comeback the bbc has said ...
Actual label:entertainment
Predicted label: entertainment

everton s weir cools euro hopes everton defender d ...
Actual label:sport
Predicted label: sport

bbc poll indicates economic gloom citizens in a ma ...
Actual label:business
Predicted label: business

talks aim to avert pension strike talks aimed at a ...
Actual label:politics
Predicted label: politics

mixed signals from french economy the french econo ...
Actual label:business
Predicted label: business

poll idols  face first hurdles vote for me - itv1  ...
Actual label:politics
Predicted label: politics

unilever shake up as profit slips anglo-dutch cons ...
Actual label:business
Predicted label: business

gazprom  in $36m back-tax claim  the nuclear unit  ...
Actual label:business

In [0]:
test_text.iloc[5]

'ultimate game  award for doom 3 sci-fi shooter doom 3 has blasted away the competition at a major games ceremony  the golden joystick awards.  it was the only title to win twice  winning ultimate game of the year and best pc game at the awards  presented by little britain star matt lucas. the much-anticipated sci-fi horror doom 3 shot straight to the top of the uk games charts on its release in august. other winners included grand theft auto: san andreas which took the most wanted for christmas prize. only released last week  it was closely followed by halo 2 and half-life 2  which are expected to be big hits when they are unleashed later this month.  but they missed out on the prize for the most wanted game of 2005  which went to the nintendo title  the legend of zelda. the original doom  released in 1994  heralded a new era in computer games and introduced 3d graphics. it helped to establish the concept of the first-person shooter. doom 3 was developed over four years and is thought

In [54]:
prediction = model.predict(np.array([x_test[3]]))
prediction

array([[9.6078136e-04, 9.3300268e-04, 2.3036113e-04, 9.9751377e-01,
        3.6206053e-04]], dtype=float32)

In [55]:
predicted_label = text_labels[np.argmax(prediction)]
predicted_label

'sport'

In [56]:
print(test_text.iloc[3][:50], "...")
print('Actual label:' + test_cat.iloc[3])
print("Predicted label: " + predicted_label + "\n") 

everton s weir cools euro hopes everton defender d ...
Actual label:sport
Predicted label: sport

